import { useEffect, useState } from 'react'
import type { EmployeeProfile } from '../../auth/types'
import { assignChannel, createChannel, listChannels, listEmployees, setChannelStatus, unassignChannel, type CommunicationChannel } from '../../lib/operations'
import { Button, Input, Select } from '../ui'

export function ChannelsAdmin() {
  const [channels, setChannels] = useState<CommunicationChannel[]>([]); const [employees, setEmployees] = useState<EmployeeProfile[]>([]); const [phone, setPhone] = useState(''); const [label, setLabel] = useState(''); const [type, setType] = useState<'whatsapp'|'phone'>('whatsapp'); const [error, setError] = useState<string>()
  const load = () => Promise.all([listChannels(), listEmployees()]).then(([c,e]) => { setChannels(c); setEmployees(e) }).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Unable to load numbers.'))
  useEffect(() => { void load() }, [])
  const mutate = (action: Promise<void>) => void action.then(load).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Update failed.'))
  return <main className="mx-auto max-w-[1300px] p-4 sm:p-7"><h1 className="text-2xl font-bold">Communication Numbers</h1><form className="mt-4 flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4" onSubmit={(e) => { e.preventDefault(); mutate(createChannel({ phone, label, type })); setPhone(''); setLabel('') }}><label className="grid gap-1 text-sm">Phone<Input required placeholder="+905551112233" value={phone} onChange={(e) => setPhone(e.target.value)} /></label><label className="grid gap-1 text-sm">Type<Select value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="whatsapp">WhatsApp</option><option value="phone">Phone</option></Select></label><label className="grid gap-1 text-sm">Label<Input value={label} onChange={(e) => setLabel(e.target.value)} /></label><Button type="submit" variant="primary">Create number</Button></form>{error && <p role="alert" className="mt-3 text-red-700">{error}</p>}<div className="mt-4 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b text-stone-500"><th className="p-3">Phone</th><th>Type</th><th>Status</th><th>Current assignee</th><th>Assignment date</th><th>Assignment</th></tr></thead><tbody>{channels.map((channel) => <tr key={channel.id} className="border-b"><td className="p-3 font-medium">{channel.phone_e164}</td><td>{channel.type}</td><td><Button onClick={() => mutate(setChannelStatus(channel.id, channel.status === 'active' ? 'inactive' : 'active'))}>{channel.status}</Button></td><td>{channel.current_assignment?.profile?.full_name ?? '—'}</td><td>{channel.current_assignment ? new Date(channel.current_assignment.assigned_at).toLocaleDateString() : '—'}</td><td><Select aria-label={`Assign ${channel.phone_e164}`} value={channel.current_assignment?.employee_id ?? ''} onChange={(e) => mutate(e.target.value ? assignChannel(channel.id, e.target.value) : unassignChannel(channel.id))}><option value="">Unassigned</option>{employees.filter((employee) => ['pending','active'].includes(employee.status)).map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name}</option>)}</Select></td></tr>)}</tbody></table></div></main>
}
