import { useEffect, useState } from 'react'
import type { EmployeeProfile, EmployeeStatus, UserRole } from '../../auth/types'
import { inviteEmployee, listEmployees, offboardEmployee, updateEmployee } from '../../lib/operations'
import { Button, Input, Select } from '../ui'

export function EmployeesAdmin() {
  const [employees, setEmployees] = useState<EmployeeProfile[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [error, setError] = useState<string>()
  const [inviteName, setInviteName] = useState(''); const [inviteEmail, setInviteEmail] = useState(''); const [invitePhone, setInvitePhone] = useState('')
  const load = () => listEmployees().then(setEmployees).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Unable to load employees.'))
  useEffect(() => { void load() }, [])
  const mutate = (action: Promise<void>) => void action.then(load).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Update failed.'))
  const visible = employees.filter((employee) => (!query || `${employee.full_name} ${employee.email}`.toLowerCase().includes(query.toLowerCase())) && (!status || employee.status === status))
  return <main className="mx-auto w-full min-w-0 max-w-[1400px] p-4 sm:p-7"><h1 className="text-2xl font-bold">Employees</h1><form className="mt-4 flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4" onSubmit={(event) => { event.preventDefault(); mutate(inviteEmployee({ fullName: inviteName, email: inviteEmail, workPhone: invitePhone })); setInviteName(''); setInviteEmail(''); setInvitePhone('') }}><label className="grid gap-1 text-sm">Full name<Input required value={inviteName} onChange={(e)=>setInviteName(e.target.value)}/></label><label className="grid gap-1 text-sm">Email<Input required type="email" value={inviteEmail} onChange={(e)=>setInviteEmail(e.target.value)}/></label><label className="grid gap-1 text-sm">Work phone<Input required placeholder="+905551112233" value={invitePhone} onChange={(e)=>setInvitePhone(e.target.value)}/></label><Button type="submit" variant="primary">Invite sales employee</Button></form><div className="mt-4 flex flex-wrap gap-3"><Input className="max-w-xs" aria-label="Search employees" placeholder="Search name or email" value={query} onChange={(e) => setQuery(e.target.value)} /><Select className="max-w-xs" aria-label="Filter employee status" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{['pending','active','suspended','former'].map((value) => <option key={value}>{value}</option>)}</Select></div>{error && <p role="alert" className="mt-3 text-red-700">{error}</p>}<div className="mt-4 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr className="border-b text-stone-500"><th className="p-3">Name</th><th>Email</th><th>Requested phone</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((employee) => <tr key={employee.id} className="border-b"><td className="p-3 font-medium"><Input defaultValue={employee.full_name} onBlur={(e) => e.target.value.trim() !== employee.full_name && mutate(updateEmployee(employee.id, { full_name: e.target.value.trim() }))} /></td><td>{employee.email}</td><td>{employee.requested_phone_e164}</td><td><Select value={employee.role} onChange={(e) => mutate(updateEmployee(employee.id, { role: e.target.value as UserRole }))}><option>SALES</option><option>ADMIN</option></Select></td><td><Select value={employee.status} onChange={(e) => { const value=e.target.value as EmployeeStatus; mutate(value === 'suspended' || value === 'former' ? offboardEmployee(employee.id, value) : updateEmployee(employee.id, { status: value })) }}>{['pending','active','suspended','former'].map((value) => <option key={value}>{value}</option>)}</Select></td><td><Button onClick={() => mutate(updateEmployee(employee.id, { status: 'active' }))}>Activate</Button></td></tr>)}</tbody></table></div></main>
}
